# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/comms.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/comms.proto',
  package='rc2',
  serialized_pb='\n\x11proto/comms.proto\x12\x03rc2\"\x8a\x01\n\x08Waypoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\x12*\n\toperation\x18\x04 \x01(\x0e\x32\x17.rc2.Waypoint.Operation\"1\n\tOperation\x12\t\n\x05NO_OP\x10\x00\x12\x0b\n\x07TOOL_ON\x10\x01\x12\x0c\n\x08TOOL_OFF\x10\x02\"\x7f\n\x07Request\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x18.rc2.Request.RequestType:\x04PING\x12\x1f\n\x08waypoint\x18\x02 \x01(\x0b\x32\r.rc2.Waypoint\"%\n\x0bRequestType\x12\x08\n\x04PING\x10\x00\x12\x0c\n\x08WAYPOINT\x10\x01\"s\n\x08Response\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32\x1c.rc2.Response.ResponseStatus:\x07SUCCESS\"0\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x42\x19\n\x10\x63om.pascucci.rc2B\x05\x43omms')



_WAYPOINT_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='rc2.Waypoint.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_OP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOOL_ON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOOL_OFF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=116,
  serialized_end=165,
)

_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='rc2.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAYPOINT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=257,
  serialized_end=294,
)

_RESPONSE_RESPONSESTATUS = _descriptor.EnumDescriptor(
  name='ResponseStatus',
  full_name='rc2.Response.ResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=363,
  serialized_end=411,
)


_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='rc2.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='rc2.Waypoint.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='rc2.Waypoint.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='rc2.Waypoint.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='rc2.Waypoint.operation', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WAYPOINT_OPERATION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=165,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='rc2.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rc2.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoint', full_name='rc2.Request.waypoint', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=294,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='rc2.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rc2.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_RESPONSESTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=296,
  serialized_end=411,
)

_WAYPOINT.fields_by_name['operation'].enum_type = _WAYPOINT_OPERATION
_WAYPOINT_OPERATION.containing_type = _WAYPOINT;
_REQUEST.fields_by_name['type'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST.fields_by_name['waypoint'].message_type = _WAYPOINT
_REQUEST_REQUESTTYPE.containing_type = _REQUEST;
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_RESPONSESTATUS
_RESPONSE_RESPONSESTATUS.containing_type = _RESPONSE;
DESCRIPTOR.message_types_by_name['Waypoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Waypoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WAYPOINT

  # @@protoc_insertion_point(class_scope:rc2.Waypoint)

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:rc2.Request)

class Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

  # @@protoc_insertion_point(class_scope:rc2.Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\020com.pascucci.rc2B\005Comms')
# @@protoc_insertion_point(module_scope)
